### ISSUE TITLE
Sending invite causes calendar to go read-only, invitation isn't sent

### ISSUE THREAD

**Issue by andrewperrin** [ExchangeCalendar/exchangecalendar#271]
This is an intermittent problem - it happens about 2/3 of the time, and I have not yet been able to determine what the specific conditions are. 

My organization's calendar is hosted by outlook.office365.com. When I invite someone from another organization that is also hosted by outlook.office365.com, most of the time the invitation isn't sent and my calendar reverts to read-only. Resetting my calendar lets it go back to read-write, but doesn't send the invitation or update it locally. This does not seem to be a problem when inviting someone within my organization or when inviting someone outside office365 (e.g., inviting someone who uses Google Calendar).
I believe the following is the log produced when this failure occurs (I've replaced my email address with (me) and the invtiee's with (invitee):

```
ExchangeCalendar [2019-04-10T19:18:31.845Z]: 6dae9716-c688-448d-aae8-abfaac50ca79: : ExchangeRequest.loadend :loadend, readyState:4, status:200
ExchangeCalendar [2019-04-10T19:18:32.917Z]: [UNC] getFreeBusyIntervals: mailto:(invitee), aBusyTypes:14, aRangeStart:2019/04/17 00:00:00 America/New_York isDate=0 nativeTime=1555473600000000, aRangeEnd:2019/05/03 00:00:00 America/New_York isDate=0 nativeTime=1556856000000000 (getFreeBusyIntervals in mivExchangeCalendar.js:3184)
ExchangeCalendar [2019-04-10T19:18:33.066Z]: e6712aad-2426-4c31-8f97-3f3bbfcfd188: : 1 ExchangeRequest.sendRequest : user=(me), url=https://outlook.office365.com/EWS/Exchange.asmx
ExchangeCalendar [2019-04-10T19:18:33.069Z]: e6712aad-2426-4c31-8f97-3f3bbfcfd188: We have a prePassword: *******
ExchangeCalendar [2019-04-10T19:18:33.073Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
ExchangeCalendar [2019-04-10T19:18:33.076Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
ExchangeCalendar [2019-04-10T19:18:33.078Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
ExchangeCalendar [2019-04-10T19:18:33.081Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
ExchangeCalendar [2019-04-10T19:18:33.084Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
ExchangeCalendar [2019-04-10T19:18:33.087Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
ExchangeCalendar [2019-04-10T19:18:33.090Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
ExchangeCalendar [2019-04-10T19:18:33.092Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
ExchangeCalendar [2019-04-10T19:18:33.095Z]: e6712aad-2426-4c31-8f97-3f3bbfcfd188: ecExchangeRequest observe: http-on-modify-request for URI https://(me):***@outlook.office365.com/EWS/Exchange.asmx, originalURI https://(me):***@outlook.office365.com/EWS/Exchange.asmx
ExchangeCalendar [2019-04-10T19:18:33.098Z]: e6712aad-2426-4c31-8f97-3f3bbfcfd188: ecExchangeRequest observe: unblocking request
ExchangeCalendar [2019-04-10T19:18:33.100Z]: 6dae9716-c688-448d-aae8-abfaac50ca79: ecExchangeRequest observe: http-on-modify-request for URI https://(me):***@outlook.office365.com/EWS/Exchange.asmx, originalURI https://(me):***@outlook.office365.com/EWS/Exchange.asmx
ExchangeCalendar [2019-04-10T19:18:33.103Z]: 6dae9716-c688-448d-aae8-abfaac50ca79: ecExchangeRequest observe: already unblocked
ExchangeCalendar [2019-04-10T19:18:33.106Z]: 38ff6c9b-60d2-4796-aeb7-c0ad8e597121: ecExchangeRequest observe: http-on-modify-request for URI https://(me):***@outlook.office365.com/EWS/Exchange.asmx, originalURI https://(me):***@outlook.office365.com/EWS/Exchange.asmx
ExchangeCalendar [2019-04-10T19:18:33.109Z]: 38ff6c9b-60d2-4796-aeb7-c0ad8e597121: ecExchangeRequest observe: already unblocked
ExchangeCalendar [2019-04-10T19:18:33.111Z]: 553dd5c8-e92a-4f7b-8d98-eabea7d7f896: ecExchangeRequest observe: http-on-modify-request for URI https://(me):***@outlook.office365.com/EWS/Exchange.asmx, originalURI https://(me):***@outlook.office365.com/EWS/Exchange.asmx
ExchangeCalendar [2019-04-10T19:18:33.114Z]: 553dd5c8-e92a-4f7b-8d98-eabea7d7f896: ecExchangeRequest observe: already unblocked
ExchangeCalendar [2019-04-10T19:18:33.117Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
ExchangeCalendar [2019-04-10T19:18:33.119Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
ExchangeCalendar [2019-04-10T19:18:33.122Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
ExchangeCalendar [2019-04-10T19:18:33.125Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8: ecnsIAuthPrompt2.getInterface: Ci.nsIApplicationCacheContainer
ExchangeCalendar [2019-04-10T19:18:33.127Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
ExchangeCalendar [2019-04-10T19:18:33.130Z]: e6712aad-2426-4c31-8f97-3f3bbfcfd188: : ExchangeRequest.loadstart
ExchangeCalendar [2019-04-10T19:18:33.134Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8: ecnsIAuthPrompt2.getInterface: Ci.nsIProgressEventSink
ExchangeCalendar [2019-04-10T19:18:33.137Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8:   --- ecnsIAuthPrompt2.onStatus: STATUS_SENDING_TO of outlook.office365.com
ExchangeCalendar [2019-04-10T19:18:33.139Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8:   --- ecnsIAuthPrompt2.onProgress: this is a nsIChannel
ExchangeCalendar [2019-04-10T19:18:33.142Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8:   --- ecnsIAuthPrompt2.onProgress:4119 of 4119
ExchangeCalendar [2019-04-10T19:18:33.145Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8:   --- ecnsIAuthPrompt2.onStatus: STATUS_WAITING_FOR of outlook.office365.com
ExchangeCalendar [2019-04-10T19:18:33.386Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
ExchangeCalendar [2019-04-10T19:18:33.390Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8:   --- ecnsIAuthPrompt2.onStatus: STATUS_RECEIVING_FROM of outlook.office365.com
ExchangeCalendar [2019-04-10T19:18:33.393Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8:   --- ecnsIAuthPrompt2.onProgress: this is a nsIChannel
ExchangeCalendar [2019-04-10T19:18:33.396Z]: 12cfa52d-e309-4e0b-81e2-d999ed946ff8:   --- ecnsIAuthPrompt2.onProgress:905 of -1
ExchangeCalendar [2019-04-10T19:18:33.400Z]: e6712aad-2426-4c31-8f97-3f3bbfcfd188: : ExchangeRequest.progress. loaded:905, total:0
ExchangeCalendar [2019-04-10T19:18:33.403Z]: e6712aad-2426-4c31-8f97-3f3bbfcfd188: : ExchangeRequest.onLoad :load, readyState:4, status:200
ExchangeCalendar [2019-04-10T19:18:33.406Z]: e6712aad-2426-4c31-8f97-3f3bbfcfd188: exchangeRequest.isHTTPRedirect.xmlReq. xmlReq.readyState:4, xmlReq.status:200
ExchangeCalendar [2019-04-10T19:18:33.414Z]: erGetUserAvailabilityRequest.onSendOk: Microsoft.Exchange.InfoWorker.Common.Availability.AddressSpaceNotFoundException: Configuration information for forest/domain (invitee's organization) could not be found in Active Directory.
   at Microsoft.Exchange.InfoWorker.Common.Availability.TargetForestConfigurationCache.FindByDomain(OrganizationId organizationId, String domainName)
   at Microsoft.Exchange.InfoWorker.Common.Availability.QueryGenerator.GetTargetForestConfiguration(EmailAddress emailAddress)
. Name of the server where exception originated: BYAPR03MB4712. LID: 47932
```

(Using 5.0.0-alpha3 for compatibility with Thunderbird (60.5.3) and Lightning (6.2.5.3). Platform is Debian Linux.)

**Comment by andrewperrin** [comment]
This issue continues - no longer intermittent, it happens each time I send such an invite.
